version: 1.0.{build}
image: Visual Studio 2019

configuration:
  - Release

build_script:
  - cmd: echo Building...

test_script:
  - cmd: echo Running tests...

deploy:
  provider: GitHub
  release: true
  artifact: path\toyourartifact.zip
  token: %GITHUB_TOKEN%
