version: 1.0.{build}
   
image: Visual Studio 2019
   
configuration:
  - Release
   
build_script:
  - npm install
  - npm run build
   
deploy:
  provider: GitHub
  repository: Elizabess/gnome-game
  on:
    branch: main
  api_key:

